# -*- coding: utf-8 -*-
"""Yolov10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_b2RUpcNnyYjecPWjgu_YcXLSvNSWpr
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics
!pip install torch torchvision

!git clone https://github.com/ultralytics/ultralytics

import torch
from ultralytics import YOLO

print(f"Using GPU: {torch.cuda.is_available()}")

model = YOLO('yolov10b.pt')  # load pretrained YOLOv10-B model
results = model.train(
    data='/content/drive/MyDrive/project/Yolov10/dataset.yaml',
    epochs=100,
    imgsz=640,
    batch=16,
    name='yolov10_helmet_detection'
)

model.export(format='onnx')

from ultralytics import YOLO

# Load model dengan weight dari 'best.pt'
model = YOLO('drive/MyDrive/project/Yolov10/best.pt')

# Start a new training process
model.train(
    data='drive/MyDrive/project/Yolov10/dataset.yaml',  # Path ke file konfigurasi dataset
    epochs=50,                # Jumlah epoch untuk fine-tuning
    batch=16,                 # Ukuran batch
    imgsz=640,                # Resolusi gambar
    optimizer='Adam',         # Optimizer
    lr0=0.0001,               # Learning rate awal
    weight_decay=0.0005       # Weight decay
)

from ultralytics import YOLO

# Load model dengan weight dari 'best.pt'
model = YOLO('drive/MyDrive/project/Yolov10/best.pt')

# Fine-tuning the model
results = model.train(
    data='drive/MyDrive/project/Yolov10/dataset.yaml',  # File YAML dataset
    epochs=50,                 # Tambahkan jumlah epoch untuk fine-tuning
    batch=16,                  # Ukuran batch
    imgsz=640,                 # Resolusi gambar
    optimizer='AdamW',         # Optimizer yang lebih stabil untuk fine-tuning
    lr0=0.0001,                # Learning rate awal
    weight_decay=0.0005,       # Regularisasi untuk mencegah overfitting
    project='drive/MyDrive/project/Yolov10/project', # Direktori penyimpanan hasil
    name='YOLOv10-X-FineTune', # Nama run
    verbose=True               # Menampilkan log pelatihan
)